version: "3"
services:
  app:
    image: app
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: ./gradlew bootRun